### ISSUE TITLE
Analysis report part 1 feedback

### ISSUE THREAD

**Issue by ugurdogrusoz** [selinfildis/CS-319-Group-21#2]
Overall it's a very nice analysis report but I am surprised to see it's missing a key part: UC descriptions! These are abstractions of the scenarios you described. In fact, your scenarios are already abstract, so they can be easily turned into UC descriptions in line with the formal format for this purpose!
[21.analysis.1.pdf](https://github.com/selinfildis/CS-319-Group-21/files/543780/21.analysis.1.pdf)

**Comment by selinfildis** [comment]
We have submitted the final version on 29th of October.
